%% Formal Plotting Figures 2, S3, S4, S5, S6, S7
clear all; clc;
addpath('cbrewer2')

icespeed = cbrewer2('seq','RdPu',100);
icespeedmod3 = icespeed(1:90,:);

surfacespeed = cbrewer2('seq','Blues',5);
basalstrength = cbrewer2('seq','Blues',5);
%% Load results

ResultsMatDir = "ResultsMatFiles";

load(fullfile(ResultsMatDir,"TempBed_Canal_50kPa.mat"),"xy","t","b","x_surf","x_base"); % Load essential independent variables for plotting

%%% Load essential dependent variables for plotting
Canal50kPa = load(fullfile(ResultsMatDir,"TempBed_Canal_50kPa.mat"),"u","u_surf","basal_tau_c_specific");

Canal100kPa = load(fullfile(ResultsMatDir,"TempBed_Canal_100kPa.mat"),"u","u_surf","basal_tau_c_specific");

Canal150kPa = load(fullfile(ResultsMatDir,"TempBed_Canal_150kPa.mat"),"u","u_surf","basal_tau_c_specific");

Canal200kPa = load(fullfile(ResultsMatDir,"TempBed_Canal_200kPa.mat"),"u","u_surf","basal_tau_c_specific");

RChannel550kPa = load(fullfile(ResultsMatDir,"SameSlope_RChannel_550kPa.mat"),"xy","t","b","x_surf","x_base","u","u_surf","basal_tau_c_specific");

RChannel520kPa = load(fullfile(ResultsMatDir,"SameSlope_RChannel_520kPa.mat"),"xy","t","b","x_surf","x_base","u","u_surf","basal_tau_c_specific");

LinkedCavity250kPa = load(fullfile(ResultsMatDir,"SameSlope_LinkedCavity_250kPa.mat"),"u","u_surf","basal_tau_c_specific");

LinkedCavity500kPa = load(fullfile(ResultsMatDir,"SameSlope_LinkedCavity_500kPa.mat"),"u","u_surf","basal_tau_c_specific");

WaterFilm4000Pa = load(fullfile(ResultsMatDir,"SameSlope_WaterFilm_4000Pa.mat"),"u","u_surf","basal_tau_c_specific");

WaterFilm5000Pa = load(fullfile(ResultsMatDir,"SameSlope_WaterFilm_5000Pa.mat"),"u","u_surf","basal_tau_c_specific");

% WaterFilm4444Pa = load(fullfile(ResultsMatDir,"SameSlope_WaterFilm_4444Pa.mat"),"u","u_surf","basal_tau_c_specific");
% 
% WaterFilm8000Pa = load(fullfile(ResultsMatDir,"SameSlope_WaterFilm_8000Pa.mat"),"u","u_surf","basal_tau_c_specific");
% 
% SingleCanal50kPa = load(fullfile(ResultsMatDir,"TempBed_only1CentralCanal_50kPa.mat"),"u","u_surf","basal_tau_c_specific");
% 
% SingleCanal100kPa = load(fullfile(ResultsMatDir,"TempBed_only1CentralCanal_100kPa.mat"),"u","u_surf","basal_tau_c_specific");
% 
% SingleCanal150kPa = load(fullfile(ResultsMatDir,"TempBed_only1CentralCanal_150kPa.mat"),"u","u_surf","basal_tau_c_specific");
% 
% SingleCanal200kPa = load(fullfile(ResultsMatDir,"TempBed_only1CentralCanal_200kPa.mat"),"u","u_surf","basal_tau_c_specific");
% 
% WiderCanal50kPa = load(fullfile(ResultsMatDir,"TempBed_CenterCanalWider_50kPa.mat"),"u","u_surf","basal_tau_c_specific");
% 
% WiderCanal100kPa = load(fullfile(ResultsMatDir,"TempBed_CenterCanalWider_100kPa.mat"),"u","u_surf","basal_tau_c_specific");
% 
% WiderCanal150kPa = load(fullfile(ResultsMatDir,"TempBed_CenterCanalWider_150kPa.mat"),"u","u_surf","basal_tau_c_specific");
% 
% WiderCanal200kPa = load(fullfile(ResultsMatDir,"TempBed_CenterCanalWider_200kPa.mat"),"u","u_surf","basal_tau_c_specific");


%% Basal Drag Profiles Fig. 2 (a) water film
figure
%yyaxis left
plot(x_base,WaterFilm4000Pa.basal_tau_c_specific/1000, ...
    '--','LineWidth',4,'DisplayName','Q = Q_0 m^3/s','Color',basalstrength(5,:), ...
    'MarkerIndices', [1 1+0.5*(size(x_base,1)-1)-40 1+0.5*(size(x_base,1)-1) 1+0.5*(size(x_base,1)-1)+40 size(x_base,1)]); hold on
plot(x_base,WaterFilm5333Pa.basal_tau_c_specific/1000, ...
    '-o','LineWidth',2,'DisplayName','Q = 0.5 Q_0 m^3/s','Color',basalstrength(3,:), ...
    'MarkerIndices', [1 1+0.5*(size(x_base,1)-1)-40 1+0.5*(size(x_base,1)-1) 1+0.5*(size(x_base,1)-1)+40 size(x_base,1)]); hold on

axis([min(x_base),max(x_base),0,1.1*max(WaterFilm4000Pa.basal_tau_c_specific/1000)])
setFontSize(14)
xlabel("Lateral direction, y [m]", FontSize=16)
ylabel("Basal drag [kPa]", FontSize=16)
legend

%% Ice Surface Speed profiles Fig. 2 (b) water film
figure;
%x_surf = xy(xy(:,2) > max(xy(:,2))-dx/100,1);
%u_surf = u(xy(:,2) > max(xy(:,2))-dx/100);
u0_norm_WF = max(WaterFilm4000Pa.u_surf); % baseline max speed for normalization
plot(x_surf,WaterFilm4000Pa.u_surf/u0_norm_WF, ...
    '--','LineWidth',4,'DisplayName','Q = Q_0 m^3/s','Color',surfacespeed(5,:), ...
    'MarkerIndices', [1 ...
    1+0.5*(length(x_surf)-1)-40 ...
    1+0.5*(length(x_surf)-1) ...
    1+0.5*(length(x_surf)-1)+40 ...
    length(x_surf)]); hold on
plot(x_surf,WaterFilm5333Pa.u_surf/u0_norm_WF, ...
    '-o','LineWidth',2,'DisplayName','Q = 0.5 Q_0 m^3/s','Color',surfacespeed(4,:), ...
    'MarkerIndices', [1 ...
    1+0.5*(length(x_surf)-1)-40 ...
    1+0.5*(length(x_surf)-1) ...
    1+0.5*(length(x_surf)-1)+40 ...
    length(x_surf)]); hold on

axis([min(xy(:,1)),max(xy(:,1)),0,1.5])
setFontSize(14)
xlabel("Lateral direction, y [m]", FontSize=16)
ylabel("Normalized ice surface speed, u/u_{max,0}", FontSize=16)
legend

%% Basal Drag Profiles Fig. 2 (c) linked cavity
figure
%yyaxis left
plot(x_base,LinkedCavity250kPa.basal_tau_c_specific/1000, ...
    '--square','LineWidth',3,'DisplayName','Q = 0.010 m^3/s','Color',basalstrength(5,:), ...
    'MarkerIndices', [1 1+0.5*(size(x_base,1)-1)-40 1+0.5*(size(x_base,1)-1) 1+0.5*(size(x_base,1)-1)+40 size(x_base,1)]); hold on
plot(x_base,LinkedCavity500kPa.basal_tau_c_specific/1000, ...
    '-v','LineWidth',3,'DisplayName','Q = 0.005 m^3/s','Color',basalstrength(3,:), ...
    'MarkerIndices', [1 1+0.5*(size(x_base,1)-1)-40 1+0.5*(size(x_base,1)-1) 1+0.5*(size(x_base,1)-1)+40 size(x_base,1)]); hold on

axis([min(x_base),max(x_base),0,1.1*max(LinkedCavity500kPa.basal_tau_c_specific/1000)])
setFontSize(14)
xlabel("Lateral direction, y [m]", FontSize=16)
ylabel("Basal drag [kPa]", FontSize=16)
legend



%% Ice Surface Speed profiles Fig. 2 (d) linked cavity
figure;
%x_surf = xy(xy(:,2) > max(xy(:,2))-dx/100,1);
%u_surf = u(xy(:,2) > max(xy(:,2))-dx/100);
u0_norm_LC = max(LinkedCavity250kPa.u_surf); % baseline max speed for normalization
plot(x_surf,LinkedCavity250kPa.u_surf/u0_norm_LC, ...
    '-square','LineWidth',3,'DisplayName','Q = 0.010 m^3/s','Color',surfacespeed(5,:), ...
    'MarkerIndices', [1 ...
    1+0.5*(length(x_surf)-1)-40 ...
    1+0.5*(length(x_surf)-1) ...
    1+0.5*(length(x_surf)-1)+40 ...
    length(x_surf)]); hold on
plot(x_surf,LinkedCavity500kPa.u_surf/u0_norm_LC, ...
    '-v','LineWidth',3,'DisplayName','Q = 0.005 m^3/s','Color',surfacespeed(3,:), ...
    'MarkerIndices', [1 ...
    1+0.5*(length(x_surf)-1)-40 ...
    1+0.5*(length(x_surf)-1) ...
    1+0.5*(length(x_surf)-1)+40 ...
    length(x_surf)]); hold on

axis([min(xy(:,1)),max(xy(:,1)),0,1.5])
setFontSize(14)
xlabel("Lateral direction, y [m]", FontSize=16)
ylabel("Normalized ice surface speed, u/u_{max,0}", FontSize=16)
legend

%% Basal Drag Profiles Fig. 2(e) and Fig. S4(c) R-Channel
figure
%yyaxis left
plot(x_base,RChannel550kPa.basal_tau_c_specific/1000, ...
    '-diamond','LineWidth',3,'DisplayName','Q = 0.086 m^3/s','Color',basalstrength(5,:), ...
    'MarkerIndices', [1 1+0.5*(size(x_base,1)-1)-40 1+0.5*(size(x_base,1)-1) 1+0.5*(size(x_base,1)-1)+40 size(x_base,1)]); hold on
plot(x_base,RChannel520kPa.basal_tau_c_specific/1000, ...
    '-^','LineWidth',3,'DisplayName','Q = 0.043 m^3/s','Color',basalstrength(3,:), ...
    'MarkerIndices', [1 1+0.5*(size(x_base,1)-1)-40 1+0.5*(size(x_base,1)-1) 1+0.5*(size(x_base,1)-1)+40 size(x_base,1)]); hold on

axis([min(x_base),max(x_base),0,1.1*max(RChannel550kPa.basal_tau_c_specific/1000)])
setFontSize(14)
xlabel("Lateral direction, y [m]", FontSize=16)
ylabel("Basal drag [kPa]", FontSize=16)
legend


%% Ice Surface Speed profiles Fig. 2(f) and Fig. S4(d) R-Channel
figure;
%x_surf = xy(xy(:,2) > max(xy(:,2))-dx/100,1);
%u_surf = u(xy(:,2) > max(xy(:,2))-dx/100);
u0_norm_RC = max(RChannel550kPa.u_surf); % baseline max speed for normalization
plot(x_surf,RChannel550kPa.u_surf/u0_norm_RC, ...
    '-diamond','LineWidth',3,'DisplayName','Q = 0.086 m^3/s','Color',surfacespeed(5,:), ...
    'MarkerIndices', [1 ...
    1+0.5*(length(x_surf)-1)-40 ...
    1+0.5*(length(x_surf)-1) ...
    1+0.5*(length(x_surf)-1)+40 ...
    length(x_surf)]); hold on
plot(x_surf,RChannel520kPa.u_surf/u0_norm_RC, ...
    '-^','LineWidth',3,'DisplayName','Q = 0.043 m^3/s','Color',surfacespeed(3,:), ...
    'MarkerIndices', [1 ...
    1+0.5*(length(x_surf)-1)-40 ...
    1+0.5*(length(x_surf)-1) ...
    1+0.5*(length(x_surf)-1)+40 ...
    length(x_surf)]); hold on

axis([min(xy(:,1)),max(xy(:,1)),0,1.5])
setFontSize(14)
xlabel("Lateral direction, y [m]", FontSize=16)
ylabel("Normalized ice surface speed, u/u_{max,0}", FontSize=16)
legend

%% Basal Drag Profiles Fig. 2(g) Canal
figure
%yyaxis left
plot(x_base,Canal50kPa.basal_tau_c_specific/1000, ...
    '--pentagram','LineWidth',4,'DisplayName','Q = 0.005 m^3/s','Color',basalstrength(5,:), ...
    'MarkerIndices', [1 1+0.5*(size(x_base,1)-1)-40 1+0.5*(size(x_base,1)-1) 1+0.5*(size(x_base,1)-1)+40 size(x_base,1)]); hold on
plot(x_base,Canal100kPa.basal_tau_c_specific/1000, ...
    '--o','LineWidth',3,'DisplayName','Q = 0.004 m^3/s','Color',basalstrength(4,:), ...
    'MarkerIndices', [1 1+0.5*(size(x_base,1)-1)-40 1+0.5*(size(x_base,1)-1) 1+0.5*(size(x_base,1)-1)+40 size(x_base,1)]); hold on
plot(x_base,Canal150kPa.basal_tau_c_specific/1000, ...
    '-square','LineWidth',2,'DisplayName','Q = 0.0025 m^3/s','Color',basalstrength(3,:), ...
    'MarkerIndices', [1 1+0.5*(size(x_base,1)-1)-40 1+0.5*(size(x_base,1)-1) 1+0.5*(size(x_base,1)-1)+40 size(x_base,1)]); hold on

axis([min(x_base),max(x_base),0,1.1*max(Canal150kPa.basal_tau_c_specific/1000)])
setFontSize(14)
xlabel("Lateral direction, y [m]", FontSize=16)
ylabel("Basal drag [kPa]", FontSize=16)
legend

%% Ice Surface Speed profiles Fig. 2(h) Canal
figure;
%x_surf = xy(xy(:,2) > max(xy(:,2))-dx/100,1);
%u_surf = u(xy(:,2) > max(xy(:,2))-dx/100);
u0_norm_Canal = max(Canal50kPa.u_surf); % baseline max speed for normalization
plot(x_surf,Canal50kPa.u_surf/u0_norm_Canal, ...
    '-pentagram','LineWidth',3,'DisplayName','Q = 0.005 m^3/s','Color',surfacespeed(5,:), ...
    'MarkerIndices', [1 ...
    1+0.5*(length(x_surf)-1)-40 ...
    1+0.5*(length(x_surf)-1) ...
    1+0.5*(length(x_surf)-1)+40 ...
    length(x_surf)]); hold on

plot(x_surf,Canal100kPa.u_surf/u0_norm_Canal, ...
    '-o','LineWidth',3,'DisplayName','Q = 0.004 m^3/s','Color',surfacespeed(4,:), ...
    'MarkerIndices', [1 ...
    1+0.5*(length(x_surf)-1)-40 ...
    1+0.5*(length(x_surf)-1) ...
    1+0.5*(length(x_surf)-1)+40 ...
    length(x_surf)]); hold on

plot(x_surf,Canal150kPa.u_surf/u0_norm_Canal, ...
    '-square','LineWidth',3,'DisplayName','Q = 0.0025 m^3/s','Color',surfacespeed(3,:), ...
    'MarkerIndices', [1 ...
    1+0.5*(length(x_surf)-1)-40 ...
    1+0.5*(length(x_surf)-1) ...
    1+0.5*(length(x_surf)-1)+40 ...
    length(x_surf)]); hold on

axis([min(xy(:,1)),max(xy(:,1)),0,1.5])
setFontSize(14)
xlabel("Lateral direction, y [m]", FontSize=16)
ylabel("Normalized ice surface speed, u/u_{max,0}", FontSize=16)
legend
